language: php

notifications:
  email: false

git:
  depth: 2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

matrix:
  include:
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
    - php: nightly
    - php: 7.1
      env: LINT=true
    - php: 7.0
    - php: 5.6

  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - if [[ $LINT = true ]]; then
      composer cs-lint;
    fi
  - composer test
